name: Release
on:
    push:
        branches:
            - master
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: ${{ secrets.registry }}
            - name: Install dependencies
              run: yarn install
            - name: Test
              run: yarn test
            - name: Build package
              run: yarn build
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
              run: npx semantic-release
